version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.2
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
